### ISSUE TITLE
训练速度问题

### ISSUE THREAD

**Issue by Yonnie1331** [yeyupiaoling/SpeechEmotionRecognition-Pytorch#1]
您好，非常感谢您的开源代码！
我不知道可能是我哪里设置有问题，我使用2000条数据，batchsize为128，训练速度特别特别慢，并且如果我使用全部数据，程序会卡住，强行停止后显示内容有fd_event_list = self._selector.poll(timeout)

**Comment by yeyupiaoling** [comment]
可能是预处理慢吧。
