### ISSUE TITLE
create_data.py问题

### ISSUE THREAD

**Issue by Vickywhy** [yeyupiaoling/SpeechEmotionRecognition-Pytorch#2]
您好，我在运行create_data.py时出现了如下错误
![image](https://github.com/yeyupiaoling/SpeechEmotionRecognition-Pytorch/assets/114728720/9324f6e9-93f7-4cdb-ae47-c7769cff59f1)
我应该如何解决这个问题

**Comment by Vickywhy** [comment]
已经解决了，请问这个可以训练中文语音的数据集吗

**Comment by yeyupiaoling** [comment]
可以的

**Comment by 3399180885** [comment]
> 已经解决了，请问这个可以训练中文语音的数据集吗

您好，请问您是怎么解决的呀？
